### ISSUE TITLE
Checken ob noch alles funktioniert

### ISSUE THREAD

**Issue by chris-len** [r-o-k-u-r-o-u/lego-praktikum#1]
Da alles durch die Kompaktor Klasse laufen soll nochmal nachsehen ob alles noch klappt.
Es gibt auch viel auskommentierten Code zum entfernen.

**Comment by r-o-k-u-r-o-u** [comment]
(In reply to comment #0)
> desc
 reply

**Comment by jimimvp** [comment]
Leuete,

heute ich kann frühestens um halb 12 kommen, weil ich eine wichtige Vorlesung habe. Ich habe ein Vorschlag. Wir sollen Primitiven für das Robot machen (Bsp. turnSoft, turnHard, rotate90, rotate180, rotate45,  centerLightSensor und so weiter), um das Robot zu steuern. Überlegen das :)
